server:
  port: 8081
  servlet:
    context-path: /

spring:
  application:
    name: service-cadastre-client-api

  datasource:
    url: jdbc:postgresql://localhost:5433/client
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  output:
    ansi:
      enabled: ALWAYS

  logging:
    level:
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE

  main:
    web-application-type: servlet

  flyway:
    enabled: true
    locations: classpath:db/migration
    # ignore-unsupported: true # Use só se necessário

  jwt:
    secret: your-very-secure-and-long-secret-key

viacep:
  url: "https://viacep.com.br/ws/"

# Kafka e outros blocos comentados...

#  http:
#    encoding:
#      charset: utf-8
#      enabled: false

#  kafka:
#    bootstrap-servers: 127.0.0.1:9092
#    consumer:
#      topics:
#        - client-create-topic
#      group-id: client-service-group
#      auto-offset: earliest
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-deserializer-org: org.apache.kafka.common.serialization.StringDeserializer
